### ISSUE TITLE
Build fails on ubuntu 16.04

### ISSUE THREAD

**Issue by cholcombe973** [tov/libffi-sys-rs#2]
It's likely that I broke my system while doing an upgrade from 14.04 -> 16.04.  Here's the output from a libffi build:

```

--- stderr
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:31: installing './compile'
configure.ac:19: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: WARNING: unrecognized options: --disable-docs
configure: WARNING: unrecognized options: --disable-docs
configure: WARNING: unrecognized options: --disable-docs
../src/closures.c: In function ‘dlmmap_locked’:
../src/closures.c:488:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
../src/closures.c:500:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
/home/chris/repos/Gfapi-sys/target/debug/build/libffi-sys-119d5af33d831421/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:114:3: error: unknown type name 'size_t'
/home/chris/repos/Gfapi-sys/target/debug/build/libffi-sys-119d5af33d831421/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:292:1: error: unknown type name 'size_t'
/home/chris/repos/Gfapi-sys/target/debug/build/libffi-sys-119d5af33d831421/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:305:1: error: unknown type name 'size_t'
/home/chris/repos/Gfapi-sys/target/debug/build/libffi-sys-119d5af33d831421/out/libffi-root/lib/libffi-3.2.1/include/ffi.h:333:26: error: unknown type name 'size_t'
thread 'main' panicked at '
        **********
        Bindgen generation failed. Please file a bug report.
        **********
    : ()', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:868
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

I'm not sure how size_t couldn't be found because I can create hello-world.c files that include size_t and they compile just fine.

**Comment by tov** [comment]
That's pretty weird. I'll look into it.

**Comment by cholcombe973** [comment]
It works fine on a fresh 16.04 install. I'm sure the upgrade broke
something I'm just not sure what

**Comment by tov** [comment]
Yeah, I can’t reproduce on my nearly-fresh Ubuntu 16.04 install. What are you using it for?

**Comment by cholcombe973** [comment]
I'm using it for my gluster bindings to do asynchronous io.
Here's a link to it:
https://github.com/cholcombe973/Gfapi-sys/blob/master/src/gluster.rs#L330

**Comment by cholcombe973** [comment]
I've got a PR up that fixes my issue.  I haven't pinned down the exact reason but upgrading bindgen to the latest does the trick.

**Comment by tov** [comment]
Btw, I’m glad you’re getting use out of it. I didn’t know if anyone was. Cool!

**Comment by cholcombe973** [comment]
Yup!  It's going to become crucial for the gluster api async functionality
once I get onto writing that :)

**Comment by tov** [comment]
Does libffi-sys-rs work for you now? It's working fine for me on my two machines, but on Travis I'm getting this:

```
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.14.0/src/lib.rs:1334
```

Googling the error message led to a #rust log where you asked about this error message. Did you ever figure it out?

**Comment by cholcombe973** [comment]
Wow. Well I might've solved it by deleting and reinstalling my tool chain.
That's not really an answer for Travis though.

My projects build now. I haven't tried to run the binary yet. I'll give
that a shot tomorrow and let you know

On Mar 2, 2017 5:23 PM, "Jesse A. Tov" <notifications@github.com> wrote:

Does libffi-sys-rs work for you now? It's working fine for me on my two
machines, but on Travis I'm getting this:

thread 'main' panicked at 'function not loaded:
clang_Type_getNumTemplateArguments',
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.14.0/src/lib.rs:1334

Googling the error message led to a #rust log where you asked about this
error message. Did you ever figure it out?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tov/libffi-sys-rs/issues/2#issuecomment-283836923>, or mute
the thread

**Comment by cholcombe973** [comment]
Seems to work fine for me.  I'm not exercising the libffi code though so there could be bugs lurking.
